export const ErrorsArray = [
    {name :"Success" , code : 1 },
    {name :"Failed" , code : 101 },
    {name :"CreationFailed" , code : 102 },
    {name :"UpdateFailed" , code : 103 },
    {name :"DeleteFailed" , code : 104 },
    {name :"Could_Not_Map_Data" , code : 105 },
    {name :"NotFound" , code : 106 },
    {name :"NotEnoughData" , code : 107 },
    {name :"InvalidId" , code : 108 },
    {name :"AuthenticationFailed" , code : 109 },
    {name :"UserNotAllowed" , code : 110 },
    {name :"AlreadyExist" , code : 111 },
    {name :"UserNotFound" , code : 112 },
    {name :"FileIsNotImage" , code : 113 },
    {name :"PhotoIsTooLarge" , code : 114 },
    {name :"CategoryNotFound" , code : 115 },
    {name :"TitleRequired" , code : 116 },
    {name :"ContentRequired" , code : 117 },
    {name :"CommentorNameRequired" , code : 118 },
    {name :"ArticleNotFound" , code : 119 },
    {name :"VideoNameRequired" , code : 120 },
    {name :"VideoThumbnailRequired" , code : 121 },
    {name :"LogoNameRequired" , code : 122 },
    {name :"SiteAddressRequired" , code : 123 },
    {name :"SiteEmailRequired" , code : 124 },
    {name :"SiteMobileRequired" , code : 125 },
    {name :"ImageNameRequired" , code : 126 },
    {name :"SocialAddressRequired" , code : 127 },
    {name :"SocialTypeRequired" , code : 128 },
    {name :"IconRequired" , code : 129 },
    {name :"DoctorNotFound" , code : 130 },
    {name :"DoctorIdRequired" , code : 131 },
    {name :"RateRequired" , code : 132 },
    {name :"ImageNotFound" , code : 133 },
    {name :"QuestionRequired" , code : 134 },
    {name :"AnswerRequired" , code : 135 },
    {name :"FileUrlRequired" , code : 136 },
    {name :"DateRequired" , code : 137 },
    {name :"StartTimeRequired" , code : 138 },
    {name :"EndTimeRquired" , code : 139 },
    {name :"AppointmentIdRequired" , code : 140 },
    {name :"ConsultingQuestionIdRquired" , code : 141 },
    {name :"PatientNotFound" , code : 142 },
    {name :"ClinicAddressRequired" , code : 143 },
    {name :"ClinicPhoneRequired" , code : 144 },
    {name :"DoctorWorkScheduleIdRequired" , code : 145 },
    {name :"ClinicLocationIdRequired" , code : 146 },
    {name :"DayOfWeekRequired" , code : 147 },
    {name :"CategoryIdRequired" , code : 148 },
    {name :"VideoContentIdRequired" , code : 149 },
    {name :"PersonnelNotFound" , code : 150 },
    {name :"LanguageTypeRequired" , code : 151 },
    {name :"DoctorWorkScheduleNotFound" , code : 152 },
    {name :"DoctorWorkTimeNotFound" , code : 153 },
    {name :"StartDateRequired" , code : 154 },
    {name :"EndDateRequired" , code : 155 },
    {name :"IncorrectPassword" , code : 156 },
    {name :"NewPasswordDoesNotMatch" , code : 157 },
    {name :"PasswordMismatch" , code : 158 },
    {name :"InvalidEmail" , code : 159 },
    {name :"InvalidToken" , code : 160 },
    {name :"PasswordRequiresDigit" , code : 161 },
    {name :"PasswordRequiresLower" , code : 162 },
    {name :"PasswordRequiresNonAlphanumeric" , code : 163 },
    {name :"PasswordRequiresUniqueChars" , code : 164 },
    {name :"PasswordRequiresUpper" , code : 165 },
    {name :"PasswordTooShort" , code : 166 },
    {name :"RecoveryCodeRedemptionFailed" , code : 167 },
    {name :"PhoneConfirmationFailed" , code : 168 },
    {name :"NoStatus" , code : 169 },
] 

export const Errors = {
    Success : 1 ,
    Failed : 101 ,
    CreationFailed : 102 ,
    UpdateFailed : 103 ,
    DeleteFailed : 104 ,
    Could_Not_Map_Data : 105 ,
    NotFound : 106 ,
    NotEnoughData : 107 ,
    InvalidId : 108 ,
    AuthenticationFailed : 109 ,
    UserNotAllowed : 110 ,
    AlreadyExist : 111 ,
    UserNotFound : 112 ,
    FileIsNotImage : 113 ,
    PhotoIsTooLarge : 114 ,
    CategoryNotFound : 115 ,
    TitleRequired : 116 ,
    ContentRequired : 117 ,
    CommentorNameRequired : 118 ,
    ArticleNotFound : 119 ,
    VideoNameRequired : 120 ,
    VideoThumbnailRequired : 121 ,
    LogoNameRequired : 122 ,
    SiteAddressRequired : 123 ,
    SiteEmailRequired : 124 ,
    SiteMobileRequired : 125 ,
    ImageNameRequired : 126 ,
    SocialAddressRequired : 127 ,
    SocialTypeRequired : 128 ,
    IconRequired : 129 ,
    DoctorNotFound : 130 ,
    DoctorIdRequired : 131 ,
    RateRequired : 132 ,
    ImageNotFound : 133 ,
    QuestionRequired : 134 ,
    AnswerRequired : 135 ,
    FileUrlRequired : 136 ,
    DateRequired : 137 ,
    StartTimeRequired : 138 ,
    EndTimeRquired : 139 ,
    AppointmentIdRequired : 140 ,
    ConsultingQuestionIdRquired : 141 ,
    PatientNotFound : 142 ,
    ClinicAddressRequired : 143 ,
    ClinicPhoneRequired : 144 ,
    DoctorWorkScheduleIdRequired : 145 ,
    ClinicLocationIdRequired : 146 ,
    DayOfWeekRequired : 147 ,
    CategoryIdRequired : 148 ,
    VideoContentIdRequired : 149 ,
    PersonnelNotFound : 150 ,
    LanguageTypeRequired : 151 ,
    DoctorWorkScheduleNotFound : 152 ,
    DoctorWorkTimeNotFound : 153 ,
    StartDateRequired : 154 ,
    EndDateRequired : 155 ,
    IncorrectPassword : 156 ,
    NewPasswordDoesNotMatch : 157 ,
    PasswordMismatch : 158 ,
    InvalidEmail : 159 ,
    InvalidToken : 160 ,
    PasswordRequiresDigit : 161 ,
    PasswordRequiresLower : 162 ,
    PasswordRequiresNonAlphanumeric : 163 ,
    PasswordRequiresUniqueChars : 164 ,
    PasswordRequiresUpper : 165 ,
    PasswordTooShort : 166 ,
    RecoveryCodeRedemptionFailed : 167 ,
    PhoneConfirmationFailed : 168 ,
    NoStatus : 169 ,
}


export const ErrorsByCode = {
    1 : "Success" ,
    101 : "Failed" ,
    102 : "CreationFailed" ,
    103 : "UpdateFailed" ,
    104 : "DeleteFailed" ,
    105 : "Could_Not_Map_Data" ,
    106 : "NotFound" ,
    107 : "NotEnoughData" ,
    108 : "InvalidId" ,
    109 : "AuthenticationFailed" ,
    110 : "UserNotAllowed" ,
    111 : "AlreadyExist" ,
    112 : "UserNotFound" ,
    113 : "FileIsNotImage" ,
    114 : "PhotoIsTooLarge" ,
    115 : "CategoryNotFound" ,
    116 : "TitleRequired" ,
    117 : "ContentRequired" ,
    118 : "CommentorNameRequired" ,
    119 : "ArticleNotFound" ,
    120 : "VideoNameRequired" ,
    121 : "VideoThumbnailRequired" ,
    122 : "LogoNameRequired" ,
    123 : "SiteAddressRequired" ,
    124 : "SiteEmailRequired" ,
    125 : "SiteMobileRequired" ,
    126 : "ImageNameRequired" ,
    127 : "SocialAddressRequired" ,
    128 : "SocialTypeRequired" ,
    129 : "IconRequired" ,
    130 : "DoctorNotFound" ,
    131 : "DoctorIdRequired" ,
    132 : "RateRequired" ,
    133 : "ImageNotFound" ,
    134 : "QuestionRequired" ,
    135 : "AnswerRequired" ,
    136 : "FileUrlRequired" ,
    137 : "DateRequired" ,
    138 : "StartTimeRequired" ,
    139 : "EndTimeRquired" ,
    140 : "AppointmentIdRequired" ,
    141 : "ConsultingQuestionIdRquired" ,
    142 : "PatientNotFound" ,
    143 : "ClinicAddressRequired" ,
    144 : "ClinicPhoneRequired" ,
    145 : "DoctorWorkScheduleIdRequired" ,
    146 : "ClinicLocationIdRequired" ,
    147 : "DayOfWeekRequired" ,
    148 : "CategoryIdRequired" ,
    149 : "VideoContentIdRequired" ,
    150 : "PersonnelNotFound" ,
    151 : "LanguageTypeRequired" ,
    152 : "DoctorWorkScheduleNotFound" ,
    153 : "DoctorWorkTimeNotFound" ,
    154 : "StartDateRequired" ,
    155 : "EndDateRequired" ,
    156 : "IncorrectPassword" ,
    157 : "NewPasswordDoesNotMatch" ,
    158 : "PasswordMismatch" ,
    159 : "InvalidEmail" ,
    160 : "InvalidToken" ,
    161 : "PasswordRequiresDigit" ,
    162 : "PasswordRequiresLower" ,
    163 : "PasswordRequiresNonAlphanumeric" ,
    164 : "PasswordRequiresUniqueChars" ,
    165 : "PasswordRequiresUpper" ,
    166 : "PasswordTooShort" ,
    167 : "RecoveryCodeRedemptionFailed" ,
    168 : "PhoneConfirmationFailed" ,
    169 : "NoStatus" ,
}
export const ErrorsByCodeFA = {
    1 : "Success" ,
    101 : "عملیات با شکست رو به رو شد" ,
    102 : "افزودن با شکست رو به رو شد" ,
    103 : "آپدیت به خطا برخورد" ,
    104 : "حذف به خطا برخورد" ,
    105 : "Could_Not_Map_Data" ,
    106 : "پیدا نشد" ,
    107 : "اطلاعات کافی نمیباشد" ,
    108 : "آیدی ناشناخته" ,
    109 : "AuthenticationFailed" ,
    110 : "کاربر اجازه ندارد" ,
    111 : "موجود است" ,
    112 : "کاربر یافت نشد" ,
    113 : "فایل عکس نمیباشد" ,
    114 : "تصویر بزرگ است" ,
    115 : "دسته بندی پیدا نشد" ,
    116 : "تیتر نیاز است" ,
    117 : "جزئیات نیاز میباشد" ,
    118 : "CommentorNameRequired" ,
    119 : "ArticleNotFound" ,
    120 : "VideoNameRequired" ,
    121 : "VideoThumbnailRequired" ,
    122 : "LogoNameRequired" ,
    123 : "SiteAddressRequired" ,
    124 : "SiteEmailRequired" ,
    125 : "SiteMobileRequired" ,
    126 : "ImageNameRequired" ,
    127 : "SocialAddressRequired" ,
    128 : "SocialTypeRequired" ,
    129 : "IconRequired" ,
    130 : "DoctorNotFound" ,
    131 : "DoctorIdRequired" ,
    132 : "RateRequired" ,
    133 : "ImageNotFound" ,
    134 : "QuestionRequired" ,
    135 : "AnswerRequired" ,
    136 : "FileUrlRequired" ,
    137 : "DateRequired" ,
    138 : "StartTimeRequired" ,
    139 : "EndTimeRquired" ,
    140 : "AppointmentIdRequired" ,
    141 : "ConsultingQuestionIdRquired" ,
    142 : "PatientNotFound" ,
    143 : "ClinicAddressRequired" ,
    144 : "ClinicPhoneRequired" ,
    145 : "DoctorWorkScheduleIdRequired" ,
    146 : "ClinicLocationIdRequired" ,
    147 : "DayOfWeekRequired" ,
    148 : "CategoryIdRequired" ,
    149 : "VideoContentIdRequired" ,
    150 : "PersonnelNotFound" ,
    151 : "LanguageTypeRequired" ,
    152 : "DoctorWorkScheduleNotFound" ,
    153 : "DoctorWorkTimeNotFound" ,
    154 : "StartDateRequired" ,
    155 : "EndDateRequired" ,
    156 : "IncorrectPassword" ,
    157 : "NewPasswordDoesNotMatch" ,
    158 : "PasswordMismatch" ,
    159 : "InvalidEmail" ,
    160 : "InvalidToken" ,
    161 : "PasswordRequiresDigit" ,
    162 : "PasswordRequiresLower" ,
    163 : "PasswordRequiresNonAlphanumeric" ,
    164 : "PasswordRequiresUniqueChars" ,
    165 : "PasswordRequiresUpper" ,
    166 : "PasswordTooShort" ,
    167 : "RecoveryCodeRedemptionFailed" ,
    168 : "PhoneConfirmationFailed" ,
    169 : "NoStatus" ,
}


// Language: javascript